export const general = [
  {
    name: 'Status',
    fieldType: 'toggle',
    type: ['folder', 'file'],
    categories: ['movies', 'songs', 'series', 'sports'],
    options: ['Active', 'Inactive'],
  },
  {
    name: 'Type',
    fieldType: 'dropdown',
    type: ['folder'],
    categories: ['movies', 'songs', 'series', 'sports'],
    options: ['movies', 'series', 'promo', 'songs', 'sports'],
  },
  {
    name: 'Production',
    fieldType: 'dropdown',
    type: ['folder'],
    categories: ['movies', 'songs', 'series'],
    options: ['Balaji', 'KK films', 'AK production', 'SKF', 'FOX'],
  },
  {
    name: 'Certification',
    fieldType: 'dropdown',
    type: ['folder', 'file'],
    categories: ['movies', 'songs', 'promos', 'commercial', 'series', 'sports'],
    options: ['U', 'U/A', 'A'],
  },
  {
    name: 'Maker',
    fieldType: 'text',
    type: ['folder'],
    categories: ['movies', 'songs', 'series'],
    options: [],
  },
  {
    name: 'Classification',
    fieldType: 'checkbox',
    type: ['folder', 'file'],
    categories: ['movies', 'songs', 'series', 'sports'],
    options: [],
  },
  {
    name: 'Languages',
    fieldType: 'checkbox multi select',
    type: ['folder', 'file', 'folder'],
    categories: ['movies', 'songs', 'series', 'sports'],
    options: ['English', 'Spanish', 'Hindi', 'Tamil', 'Marathi'],
  },
  {
    name: 'Slot Duration',
    fieldType: 'time',
    type: ['folder', 'file', 'folder'],
    categories: ['movies', 'songs', 'promos', 'series', 'sports'],
    options: [],
  },
  {
    name: 'Orig. Duration',
    fieldType: 'time',
    type: ['folder', 'folder'],
    categories: ['movies', 'songs', 'series', 'sports'],
    options: [],
  },
  {
    name: 'TX Run Time',
    fieldType: 'time',
    type: ['folder', 'file', 'folder'],
    categories: ['movies', 'songs', 'series', 'sports'],
    options: [],
  },
  {
    name: 'Content',
    fieldType: 'text',
    type: ['folder', 'folder'],
    categories: ['movies', 'series'],
    options: [],
  },
  {
    name: 'External Ref. No.',
    fieldType: 'alpha numeric',
    type: ['folder', 'folder'],
    categories: ['movies', 'songs', 'series', 'sports'],
    options: [],
  },
  {
    name: 'Prod. Year',
    fieldType: 'year',
    type: ['folder', 'folder'],
    categories: ['movies', 'songs', 'series'],
    options: [],
  },
  {
    name: 'Barcode',
    fieldType: 'text',
    type: ['folder', 'file', 'folder'],
    categories: ['movies', 'songs', 'series', 'sports'],
    options: [],
  },
  {
    name: 'TX ID',
    fieldType: 'alpha numeric',
    type: ['folder', 'file', 'folder'],
    categories: ['movies', 'songs', 'series', 'sports'],
    options: [],
  },
  {
    name: 'Work List Status',
    fieldType: 'dropdown',
    type: ['file', 'folder'],
    categories: ['movies', 'songs', 'series', 'sports'],
    options: ['Not started', 'Completed', 'In progress'],
  },
  {
    name: 'External Reference',
    fieldType: 'alpha numeric',
    type: ['file', 'folder'],
    categories: ['movies', 'songs', 'series', 'sports'],
    options: [],
  },
  {
    name: 'Aspect Ratio',
    fieldType: 'dropdown',
    type: ['file', 'folder'],
    categories: ['movies', 'songs', 'series', 'sports'],
    options: ['4:3', '16:9', '1:85:1'],
  },
  {
    name: 'TX Parts',
    fieldType: 'text',
    type: ['file', 'folder'],
    categories: ['movies', 'songs', 'series', 'sports'],
    options: [],
  },
  {
    name: 'TX Approved Timings',
    fieldType: 'time',
    type: ['file', 'folder'],
    categories: ['movies', 'songs', 'series', 'sports'],
    options: [],
  },
  {
    name: 'Description',
    fieldType: 'long text',
    type: ['file', 'folder'],
    categories: ['movies', 'songs', 'series', 'sports'],
    options: [],
  },
  {
    name: 'Priority',
    fieldType: 'text',
    type: ['file'],
    categories: ['promos'],
    options: [],
  },
  {
    name: 'Created for Month',
    fieldType: 'text',
    type: ['file'],
    categories: ['promos'],
    options: [],
  },
  {
    name: 'Created for Year',
    fieldType: 'text',
    type: ['file'],
    categories: ['promos'],
    options: [],
  },
  {
    name: 'Producer',
    fieldType: 'text',
    type: ['file'],
    categories: ['promos'],
    options: [],
  },
  {
    name: 'Notes',
    fieldType: 'text',
    type: ['file'],
    categories: ['promos'],
    options: [],
  },
  {
    name: 'Duration',
    fieldType: 'text',
    type: ['file'],
    categories: ['commercial'],
    options: [],
  },
  {
    name: 'Estimated First Air Date',
    fieldType: 'text',
    type: ['file'],
    categories: ['commercial'],
    options: [],
  },
  {
    name: 'Expiry Date',
    fieldType: 'text',
    type: ['file'],
    categories: ['commercial'],
    options: [],
  },
  {
    name: 'No. of Episodes',
    fieldType: 'text',
    type: ['folder'],
    categories: ['series'],
    options: [],
  },
  {
    name: 'Genre',
    fieldType: 'dropdown',
    type: ['folder'],
    categories: ['series'],
    options: [],
  },
  {
    name: 'Seq',
    fieldType: 'text',
    type: ['folder'],
    categories: ['series'],
    options: [],
  },
  {
    name: 'TX Order',
    fieldType: 'numeric',
    type: ['folder'],
    categories: ['series'],
    options: [],
  },
  {
    name: 'Production Number',
    fieldType: 'alpha mumeric',
    type: ['folder'],
    categories: ['series'],
    options: [],
  },
  {
    name: 'Content Reference',
    fieldType: 'text',
    type: ['folder'],
    categories: ['series'],
    options: [],
  },
  {
    name: 'Quality',
    fieldType: 'text',
    type: ['folder'],
    categories: ['series'],
    options: [],
  },
  {
    name: 'Default version',
    fieldType: 'text',
    type: ['folder'],
    categories: ['series'],
    options: [],
  },
  {
    name: 'Total Versions',
    fieldType: 'text',
    type: ['folder'],
    categories: ['series'],
    options: [],
  },
  {
    name: 'Versions',
    fieldType: 'text',
    type: ['folder'],
    categories: ['series'],
    options: [],
  },
  {
    name: 'Compliance Channels',
    fieldType: 'text',
    type: ['folder'],
    categories: ['series'],
    options: [],
  },
  {
    name: 'Material Type',
    fieldType: 'text',
    type: ['folder'],
    categories: ['series'],
    options: [],
  },
  {
    name: 'Lock Segments Within The Same Part',
    fieldType: 'text',
    type: ['folder'],
    categories: ['series'],
    options: [],
  },
  {
    name: 'Part',
    fieldType: 'text',
    type: ['folder'],
    categories: ['series'],
    options: [],
  },
];
