export const technical = [
  {
    name: 'Material Identifier',
    fieldType: 'alpha numeric',
    type: ['file'],
    categories: ['movies', 'sports', 'promos', 'commercial'],
    options: [],
  },
  {
    name: 'Compliance Status',
    fieldType: 'with view compliance report option',
    type: ['file'],
    categories: ['movies', 'sports', 'promos', 'commercial'],
    options: ['Rejected', 'In progress', 'Approved'],
  },
  {
    name: 'Material Ref Id',
    fieldType: 'alpha numeric',
    type: ['file'],
    categories: ['movies', 'sports', 'promos', 'commercial'],
    options: [],
  },
  {
    name: 'Wrapper',
    fieldType: 'drop down',
    type: ['file'],
    categories: ['movies', 'sports', 'promos', 'commercial'],
    options: ['Mp4', 'mxf'],
  },
  {
    name: 'Material Dur',
    fieldType: 'time',
    type: ['file'],
    categories: ['movies', 'sports', 'promos', 'commercial'],
    options: [],
  },
  {
    name: 'Codec',
    fieldType: 'dropdown',
    type: ['file'],
    categories: ['movies', 'sports', 'promos', 'commercial'],
    options: ['H.264', 'MPEG-4 AVC'],
  },
  {
    name: 'Aspect Ratio',
    fieldType: 'dropdown',
    type: ['file'],
    categories: ['movies', 'promos', 'commercial'],
    options: ['4:3', '16:9', '1:85:1'],
  },
  {
    name: 'Bitrate',
    fieldType: 'numeric',
    type: ['file'],
    categories: ['movies', 'sports', 'promos', 'commercial'],
    options: [],
  },
  {
    name: 'Bitrate Mode',
    fieldType: 'dropdown',
    type: ['file'],
    categories: ['movies', 'sports', 'promos', 'commercial'],
    options: [],
  },
  {
    name: 'Frame Rate',
    fieldType: 'numeric',
    type: ['file'],
    categories: ['movies', 'sports', 'promos', 'commercial'],
    options: [],
  },
  {
    name: 'Display Resolution',
    fieldType: 'dropdown',
    type: ['file'],
    categories: ['movies', 'sports', 'promos', 'commercial'],
    options: ['120p', '240p', '480p', '720p', 'HD', 'HDD'],
  },
  {
    name: 'Format -- Y',
    fieldType: 'preview window',
    type: ['file'],
    categories: ['promos', 'commercial'],
    options: [],
  },
];
