export const title = [
  {
    name: 'Movie Title*',
    fieldType: 'text',
    type: ['file', 'folder'],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',
    categories: ['movies'],
    options: [],
  },
  {
    name: 'AKA Titles',
    fieldType: 'text',
    type: ['file', 'folder', 'folder'],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',
    categories: ['movies', 'songs', 'promos', 'commercial', 'series', 'events'],
    options: [],
  },
  {
    name: 'Year',
    fieldType: 'year',
    type: ['folder', 'folder'],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',
    categories: ['movies', 'songs', 'series'],
    options: [],
  },
  {
    name: 'Movie Id',
    fieldType: 'Alpha numeric',
    type: ['folder'],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',
    categories: ['movies'],
    options: [],
  },
  {
    name: 'Channel Group',
    fieldType: 'dropdown',
    type: ['folder', 'file', 'folder'],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',
    categories: ['movies', 'songs', 'promos', 'commercial', 'series', 'events'],
    options: [],
  },
  {
    name: 'Production House',
    fieldType: 'dropdown',
    type: ['folder'],
    categories: ['movies', 'songs'],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',
    options: ['Balaji', 'KK films', 'AK production', 'SKF', 'FOX'],
  },
  {
    name: 'Keywords',
    fieldType: 'text',
    type: ['folder', 'file'],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',
    categories: ['movies', 'songs', 'promos', 'commercial', 'series', 'events'],
    options: [],
  },
  {
    name: 'Version Title*',
    fieldType: 'text',
    type: ['file'],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',
    categories: ['movies', 'songs', 'promos', 'commercial'],
    options: [],
  },
  {
    name: 'Version Code',
    fieldType: 'text',
    type: ['file'],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',

    categories: ['movies'],
    options: [],
  },
  {
    name: 'TX Order',
    fieldType: 'text',
    type: ['file'],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',

    categories: ['movies', 'series'],
    options: [],
  },
  {
    name: 'Song Title*',
    fieldType: 'text',
    type: ['folder', 'file'],
    categories: ['songs'],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',

    options: [],
  },
  {
    name: 'Song ID',
    fieldType: 'text',
    type: ['folder'],
    categories: ['songs'],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',

    options: [],
  },
  {
    name: 'Album Name',
    fieldType: 'text',
    type: ['folder'],
    categories: ['songs'],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',

    options: [],
  },
  {
    name: 'duration',
    fieldType: 'text',
    type: ['folder'],
    categories: ['songs'],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',

    options: [],
  },
  {
    name: 'Promotion Title',
    fieldType: 'text',
    type: ['folder', 'file'],
    categories: ['promos'],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',

    options: [],
  },
  {
    name: 'Certification',
    fieldType: 'text',
    type: ['folder'],
    categories: ['promos'],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',

    options: [],
  },
  {
    name: 'Producer',
    fieldType: 'text',
    type: ['folder'],
    categories: ['promos'],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',

    options: [],
  },
  {
    name: 'Unpackaged Master',
    fieldType: 'text',
    type: ['folder'],
    categories: ['promos'],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',

    options: [],
  },
  {
    name: 'Timecode In',
    fieldType: 'text',
    type: ['folder'],
    categories: ['promos'],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',

    options: [],
  },
  {
    name: 'Notes',
    fieldType: 'text',
    type: ['folder'],
    categories: ['promos'],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',

    options: [],
  },
  {
    name: 'Genre',
    fieldType: 'text',
    type: ['folder'],
    categories: ['promos'],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',

    options: [],
  },
  {
    name: 'Seq',
    fieldType: 'text',
    type: ['folder'],
    categories: ['promos'],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',

    options: [],
  },
  {
    name: 'Dublist Export Date',
    fieldType: 'text',
    type: ['file'],
    categories: ['promos', 'commercial'],
    options: [],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',
  },
  {
    name: 'Event Type',
    fieldType: 'text',
    type: ['file'],
    categories: ['promos'],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',

    options: [],
  },
  {
    name: 'Production Number',
    fieldType: 'text',
    type: ['folder', 'file'],
    categories: ['promos', 'commercial', 'series'],
    options: [],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',
  },
  {
    name: 'House Number',
    fieldType: 'text',
    type: ['file', 'folder'],
    categories: ['promos', 'commercial'],
    options: [],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',
  },
  {
    name: 'Commercial Title',
    fieldType: 'text',
    type: ['file', 'folder'],
    categories: ['commercial'],
    options: [],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',
  },
  {
    name: 'Product Code',
    fieldType: 'text',
    type: ['folder', 'file'],
    categories: ['commercial'],
    options: [],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',
  },
  {
    name: 'Programme Title',
    fieldType: 'text',
    type: ['folder'],
    categories: ['series'],
    options: [],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',
  },
  {
    name: 'Season Count',
    fieldType: 'text',
    type: ['folder'],
    categories: ['series'],
    options: [],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',
  },
  {
    name: 'season No',
    fieldType: 'text',
    type: ['folder'],
    categories: ['series'],
    options: [],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',
  },
  {
    name: 'Programme Id',
    fieldType: 'text',
    type: ['folder'],
    categories: ['series'],
    options: [],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',
  },
  {
    name: 'Programme Group',
    fieldType: 'text',
    type: ['folder'],
    categories: ['series'],
    options: [],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',
  },
  {
    name: 'Series No.',
    fieldType: 'text',
    type: ['folder'],
    categories: ['series'],
    options: [],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',
  },
  {
    name: 'Episode No.',
    fieldType: 'text',
    type: ['folder'],
    categories: ['series'],
    options: [],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',
  },
  {
    name: 'Episode Title*',
    fieldType: 'text',
    type: ['folder'],
    categories: ['series'],
    options: [],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',
  },
  {
    name: 'Compilation',
    fieldType: 'text',
    type: ['folder'],
    categories: ['series'],
    options: [],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',
  },
  {
    name: 'Version Code',
    fieldType: 'text',
    type: ['folder'],
    categories: ['series'],
    options: [],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',
  },
  {
    name: 'Date',
    fieldType: 'text',
    type: ['folder', 'file'],
    categories: ['sports'],
    options: [],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',
  },
  {
    name: 'Even ID',
    fieldType: 'text',
    type: ['folder', 'file'],
    categories: ['sports'],
    options: [],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',
  },
  {
    name: 'Locations',
    fieldType: 'text',
    type: ['folder', 'file'],
    categories: ['sports'],
    options: [],
    placeholder: '',
    tabId: '63dbb9ec32608d6098187f52',
  },
];
